# Generated by Django 2.2 on 2020-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchInfo', '0002_auto_20200306_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_uri',
            field=models.ImageField(default='default.png', upload_to='player_image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_uri',
            field=models.ImageField(default='default.png', upload_to='team_logo'),
        ),
    ]
