# Generated by Django 2.2 on 2020-03-17 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchInfo', '0003_auto_20200306_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_history',
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balls_played', models.IntegerField(blank=True, null=True)),
                ('total_runs_scored', models.IntegerField(blank=True, null=True)),
                ('total_balls_bowled', models.IntegerField(blank=True, null=True)),
                ('total_wickets_taken', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matchInfo.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matchInfo.Player')),
            ],
        ),
    ]
