# Generated by Django 2.2 on 2020-03-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchInfo', '0004_auto_20200317_0306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
